# most of the heavy setup lifting is split into sub-files so we source them here
for file in ~/.dotfiles/bash/source/{options,path,prompt,exports,aliases,functions,git,webdev}; do
	[[ -r "$file" ]] && source "$file"
done
unset file

